# Welcome to Jekyll!
#

# Site settings
title: Gokul 	
description: 
  Research Scholar. Existentialist. 
owner: Gokul # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: hgokul98@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://h-gokul.github.io" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/h-gokul
  linkedin-square: https://linkedin.com/in/hgokul7
  facebook-official: https://www.facebook.com/goku.ron.7
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: hgokul98@gmail.com
  #flickr:
  instagram: https://www.instagram.com/gokul._h_/
  #youtube-square:
  # spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
